// Sample job data structure for seeding the database
export type JobSeed = {
  _id: string;
  title: string;
  company: string;
  location: string;
  work_type: string;
  description: string;
  requirements: string[];
  type: string;
  experience: string;
  salary: string;
  skills: string[];
  benefits: string[];
};

type JobSeedWithoutId = {
  title: string;
  company: string;
  location: string;
  work_type: string;
  description: string;
  requirements: string[];
  type: string;
  experience: string;
  salary: string;
  skills: string[];
  benefits: string[];
};

// Sample jobs data
export const jobs: JobSeedWithoutId[] = [
  {
    title: "Frontend Developer",
    company: "Tech Corp",
    location: "San Francisco, CA",
    work_type: "On-site",
    type: "Full-time",
    experience: "Senior",
    salary: "$100k - $130k",
    description:
      "We are looking for an experienced Frontend Developer to join our team and help build modern web applications using React and Next.js.",
    requirements: [
      "3+ years React experience",
      "TypeScript knowledge",
      "Experience with Next.js",
    ],
    skills: ["React", "TypeScript", "Next.js", "Tailwind CSS", "HTML5", "CSS3"],
    benefits: [
      "Health insurance",
      "401k",
      "Remote work option",
      "Flexible hours",
    ],
  },
  {
    title: "Backend Engineer",
    company: "Data Systems Inc",
    location: "New York, NY",
    work_type: "On-site",
    type: "Part-time",
    experience: "Lead",
    salary: "$60 - $80 per hour",
    description:
      "Seeking a skilled Backend Engineer to develop and maintain scalable server-side applications and APIs.",
    requirements: [
      "5+ years Node.js experience",
      "MongoDB expertise",
      "API design experience",
      "Microservices architecture knowledge",
    ],
    skills: [
      "Node.js",
      "MongoDB",
      "Express",
      "TypeScript",
      "REST APIs",
      "Docker",
      "AWS",
    ],
    benefits: [
      "Health & dental",
      "Stock options",
      "Gym membership",
      "Flexible schedule",
    ],
  },
  {
    title: "Full Stack Developer",
    company: "StartupX",
    location: "Boston, MA",
    work_type: "Remote",
    type: "Contract",
    experience: "Immediate",
    salary: "$90k - $120k",
    description:
      "Join our fast-growing startup as a Full Stack Developer. Help build and scale our main product using modern technologies.",
    requirements: [
      "Full stack development experience",
      "React/Next.js proficiency",
      "Node.js backend experience",
      "Database management (SQL/NoSQL)",
    ],
    skills: [
      "React",
      "Next.js",
      "Node.js",
      "MongoDB",
      "TypeScript",
      "GraphQL",
      "Git",
    ],
    benefits: [
      "Remote-first",
      "Flexible hours",
      "Learning budget",
      "Health insurance",
      "Team retreats",
    ],
  },
  {
    title: "Data Scientist",
    company: "Insight Analytics",
    location: "Austin, TX",
    work_type: "Hybrid",
    type: "Full-time",
    experience: "Senior",
    salary: "$110k - $150k",
    description:
      "Leverage data to uncover insights and drive business decisions. Develop predictive models and perform complex data analysis.",
    requirements: [
      "Master's or PhD in quantitative field",
      "Strong Python/R skills",
      "Experience with ML frameworks (TensorFlow/PyTorch)",
    ],
    skills: [
      "Python",
      "R",
      "SQL",
      "Machine Learning",
      "Statistics",
      "Data Visualization",
      "Big Data (Spark)",
    ],
    benefits: [
      "Competitive salary",
      "Comprehensive health plans",
      "Generous PTO",
      "Conference budget",
    ],
  },
  {
    title: "DevOps Engineer",
    company: "Cloud Solutions Ltd.",
    location: "Seattle, WA",
    work_type: "Remote",
    type: "Internship",
    experience: "Immediate",
    salary: "$25 - $35 per hour",
    description:
      "Implement and manage CI/CD pipelines, automate infrastructure provisioning, and ensure system reliability and scalability on AWS.",
    requirements: [
      "Experience with AWS",
      "Proficiency in scripting (Bash/Python)",
      "Knowledge of Kubernetes/Docker",
      "CI/CD tools (Jenkins/GitLab CI)",
    ],
    skills: [
      "AWS",
      "Kubernetes",
      "Docker",
      "Terraform",
      "Ansible",
      "Jenkins",
      "Python",
      "Linux",
    ],
    benefits: [
      "Flexible schedule",
      "Mentorship",
      "Possibility of full-time offer",
      "Learning stipend",
    ],
  },
  {
    title: "Marketing Manager",
    company: "Creative Buzz Agency",
    location: "London, UK",
    work_type: "On-site",
    type: "Full-time",
    experience: "Lead",
    salary: "£55k - £70k",
    description:
      "Develop and execute innovative marketing strategies across multiple channels to drive brand awareness and lead generation.",
    requirements: [
      "Proven marketing campaign experience",
      "Strong understanding of SEO/SEM",
      "Excellent communication skills",
      "Budget management",
    ],
    skills: [
      "Digital Marketing",
      "SEO",
      "SEM",
      "Content Marketing",
      "Social Media Strategy",
      "Analytics",
      "Campaign Management",
    ],
    benefits: [
      "Pension scheme",
      "Private health insurance",
      "Performance bonus",
      "Central London office",
    ],
  },
  {
    title: "UI/UX Designer",
    company: "Appify Creations",
    location: "Berlin, Germany",
    work_type: "Hybrid",
    type: "Contract",
    experience: "Senior",
    salary: "€40 - €50 per hour",
    description:
      "Design intuitive and engaging user interfaces for web and mobile applications. Conduct user research and create wireframes and prototypes.",
    requirements: [
      "Strong portfolio showcasing UI/UX work",
      "Proficiency in Figma/Sketch/Adobe XD",
      "User research methodologies",
      "Understanding of design systems",
    ],
    skills: [
      "Figma",
      "Sketch",
      "User Research",
      "Wireframing",
      "Prototyping",
      "Interaction Design",
      "Usability Testing",
    ],
    benefits: [
      "Relocation support",
      "Language courses",
      "Flexible working hours",
      "Modern office space",
    ],
  },
  {
    title: "QA Automation Engineer",
    company: "QualitySoft",
    location: "Seattle, WA",
    work_type: "On-site",
    type: "Full-time",
    experience: "Senior",
    salary: "$95k - $125k",
    description:
      "Design, develop, and execute automated test scripts to ensure software quality. Collaborate with developers to resolve issues.",
    requirements: [
      "Experience with Selenium/Cypress",
      "Programming skills (Java/Python/JavaScript)",
      "API testing knowledge",
      "Experience with test frameworks",
    ],
    skills: [
      "Selenium",
      "Cypress",
      "Java",
      "Python",
      "API Testing",
      "JIRA",
      "SQL",
      "Test Automation",
    ],
    benefits: [
      "Medical/Dental/Vision",
      "401k matching",
      "Paid volunteer time",
      "On-site gym",
    ],
  },
  {
    title: "Graphic Designer",
    company: "Visual Impact Studios",
    location: "Chicago, IL",
    work_type: "Hybrid",
    type: "Part-time",
    experience: "Immediate",
    salary: "$30 - $40 per hour",
    description:
      "Create compelling visual assets for branding, marketing materials, web, and print. Collaborate with marketing and product teams.",
    requirements: [
      "Expertise in Adobe Creative Suite (Photoshop, Illustrator, InDesign)",
      "Strong portfolio",
      "Understanding of typography and layout",
    ],
    skills: [
      "Adobe Photoshop",
      "Adobe Illustrator",
      "Adobe InDesign",
      "Branding",
      "Typography",
      "Layout Design",
      "Digital Art",
    ],
    benefits: [
      "Flexible schedule",
      "Creative environment",
      "Potential for full-time conversion",
    ],
  },
  {
    title: "Cloud Architect (Azure)",
    company: "Enterprise Cloud Partners",
    location: "Portland, OR",
    work_type: "Remote",
    type: "Full-time",
    experience: "Lead",
    salary: "$140k - $180k",
    description:
      "Design and implement scalable, secure, and robust cloud solutions on Microsoft Azure. Provide technical leadership and guidance.",
    requirements: [
      "Extensive Azure experience",
      "Strong understanding of cloud networking and security",
      "Infrastructure as Code (ARM/Terraform)",
      "Azure certifications preferred",
    ],
    skills: [
      "Azure",
      "Solution Architecture",
      "Cloud Security",
      "Networking",
      "Terraform",
      "ARM Templates",
      "DevOps Principles",
    ],
    benefits: [
      "Competitive salary",
      "Performance bonus",
      "Comprehensive benefits",
      "Remote work",
      "Professional development funds",
    ],
  },
  {
    title: "Staff Accountant",
    company: "Finance Forward LLC",
    location: "Toronto, ON",
    work_type: "On-site",
    type: "Internship",
    experience: "Immediate",
    salary: "$20 - $25 CAD per hour",
    description:
      "Manage day-to-day accounting tasks, including accounts payable/receivable, general ledger entries, and bank reconciliations.",
    requirements: [
      "Currently pursuing Bachelor's degree in Accounting/Finance",
      "Experience with accounting software (QuickBooks/Xero)",
      "Knowledge of GAAP/IFRS",
    ],
    skills: [
      "Accounting",
      "QuickBooks",
      "General Ledger",
      "Accounts Payable",
      "Accounts Receivable",
      "Financial Reporting",
      "Excel",
    ],
    benefits: [
      "Course credit",
      "Mentorship",
      "Paid internship",
      "Professional development support",
    ],
  },
  {
    title: "Mobile Developer (Android)",
    company: "ConnectApp",
    location: "Munich, Germany",
    work_type: "Remote",
    type: "Contract",
    experience: "Senior",
    salary: "€65k - €85k",
    description:
      "Develop and maintain native Android applications using Kotlin and Java. Collaborate with cross-functional teams to define and ship new features.",
    requirements: [
      "Proven Android development experience",
      "Proficiency in Kotlin/Java",
      "Experience with Android SDK and Jetpack",
      "RESTful API integration",
    ],
    skills: [
      "Android Development",
      "Kotlin",
      "Java",
      "Android SDK",
      "Jetpack Compose",
      "REST APIs",
      "Git",
      "MVVM/MVI",
    ],
    benefits: [
      "Remote work",
      "Flexible hours",
      "Stock options",
      "Health insurance contribution",
    ],
  },
  {
    title: "Human Resources Generalist",
    company: "PeopleFirst Corp",
    location: "Denver, CO",
    work_type: "Hybrid",
    type: "Part-time",
    experience: "Senior",
    salary: "$35 - $45 per hour",
    description:
      "Support various HR functions including recruitment, onboarding, employee relations, benefits administration, and compliance.",
    requirements: [
      "Bachelor's degree in HR or related field",
      "Experience with HRIS systems",
      "Knowledge of employment law",
      "Strong interpersonal skills",
    ],
    skills: [
      "Human Resources",
      "Recruitment",
      "Onboarding",
      "Employee Relations",
      "Benefits Administration",
      "HRIS",
      "Compliance",
    ],
    benefits: [
      "Health/Dental/Vision",
      "401k",
      "Paid parental leave",
      "Wellness program",
    ],
  },
  {
    title: "Cybersecurity Analyst",
    company: "Secure Networks Inc.",
    location: "Washington D.C.",
    work_type: "On-site",
    type: "Full-time",
    experience: "Immediate",
    salary: "$85k - $115k",
    description:
      "Monitor security alerts, respond to incidents, conduct vulnerability assessments, and help maintain security infrastructure.",
    requirements: [
      "Experience with SIEM tools",
      "Understanding of network protocols and security principles",
      "Incident response experience",
      "Relevant certifications (Security+, CySA+)",
    ],
    skills: [
      "Cybersecurity",
      "SIEM",
      "Incident Response",
      "Vulnerability Assessment",
      "Network Security",
      "Firewalls",
      "Intrusion Detection",
    ],
    benefits: [
      "Security clearance support (if applicable)",
      "Comprehensive health benefits",
      "Training budget",
      "401k matching",
    ],
  },
  {
    title: "Technical Writer",
    company: "DocuTech Solutions",
    location: "Minneapolis, MN",
    work_type: "Remote",
    type: "Part-time",
    experience: "Senior",
    salary: "$40 - $60 per hour",
    description:
      "Create clear, concise, and accurate technical documentation, including user manuals, API documentation, and knowledge base articles.",
    requirements: [
      "Proven technical writing experience",
      "Ability to understand complex technical concepts",
      "Experience with documentation tools (Markdown, Confluence)",
      "Excellent writing and editing skills",
    ],
    skills: [
      "Technical Writing",
      "API Documentation",
      "User Manuals",
      "Markdown",
      "Confluence",
      "Editing",
      "Information Architecture",
    ],
    benefits: [
      "Fully Remote",
      "Flexible hours",
      "Opportunity to work with diverse products",
    ],
  },
  {
    title: "IT Project Manager",
    company: "Innovate Solutions",
    location: "Boston, MA",
    work_type: "Hybrid",
    type: "Full-time",
    experience: "Lead",
    salary: "$105k - $135k",
    description:
      "Lead and manage IT projects from initiation to completion, ensuring projects are delivered on time, within scope, and on budget.",
    requirements: [
      "Experience managing software development projects",
      "Strong knowledge of Agile/Scrum methodologies",
      "Excellent communication and leadership skills",
      "PMP or CSM certification a plus",
    ],
    skills: [
      "Project Management",
      "Agile",
      "Scrum",
      "JIRA",
      "Risk Management",
      "Stakeholder Management",
      "Budgeting",
      "Software Development Lifecycle",
    ],
    benefits: [
      "Health insurance",
      "401k plan",
      "Performance bonus",
      "Hybrid work model",
    ],
  },
  {
    title: "Executive Chef",
    company: "The Grand Restaurant",
    location: "Paris, France",
    work_type: "On-site",
    type: "Full-time",
    experience: "Lead",
    salary: "€70k - €90k + bonus",
    description:
      "Oversee all kitchen operations, including menu creation, staff management, inventory control, and ensuring high standards of food quality and safety.",
    requirements: [
      "Extensive culinary experience in fine dining",
      "Proven leadership skills",
      "Knowledge of food costing and inventory management",
      "Relevant culinary degree/certification",
    ],
    skills: [
      "Culinary Arts",
      "Menu Development",
      "Kitchen Management",
      "Staff Training",
      "Food Costing",
      "Inventory Control",
      "Fine Dining",
    ],
    benefits: [
      "Performance bonus",
      "Meals provided",
      "Uniform allowance",
      "Health benefits package",
    ],
  },
  {
    title: "IT Support Specialist - Tier 2",
    company: "Global Tech Support",
    location: "Vancouver, BC",
    work_type: "Remote",
    type: "Full-time",
    experience: "Immediate",
    salary: "$55k - $70k CAD",
    description:
      "Provide technical assistance and support for incoming queries and issues related to computer systems, software, and hardware. Escalate unresolved issues.",
    requirements: [
      "Experience in IT support role",
      "Strong troubleshooting skills (Windows/Mac OS)",
      "Knowledge of Active Directory and networking concepts",
      "Excellent customer service skills",
    ],
    skills: [
      "IT Support",
      "Troubleshooting",
      "Windows OS",
      "Mac OS",
      "Active Directory",
      "Networking Basics",
      "Help Desk Software",
      "Customer Service",
    ],
    benefits: [
      "Remote work",
      "Health and dental plan",
      "Paid time off",
      "Certification reimbursement",
    ],
  },
  {
    title: "Network Engineer",
    company: "Connectivity Solutions Pte Ltd",
    location: "Singapore",
    work_type: "On-site",
    type: "Full-time",
    experience: "Senior",
    salary: "$80k - $110k SGD",
    description:
      "Design, implement, maintain, and support our growing network infrastructure. Ensure network connectivity and security.",
    requirements: [
      "Experience with Cisco/Juniper equipment",
      "Strong understanding of routing (BGP, OSPF) and switching",
      "Firewall configuration knowledge (Palo Alto/Fortinet)",
      "Network certifications (CCNA/CCNP) preferred",
    ],
    skills: [
      "Network Engineering",
      "Cisco IOS/NX-OS",
      "Juniper Junos",
      "Routing Protocols",
      "Switching",
      "Firewalls",
      "VPN",
      "Network Monitoring",
    ],
    benefits: [
      "Medical insurance",
      "Annual leave",
      "Transport allowance",
      "Training opportunities",
    ],
  },
  {
    title: "Registered Nurse (ER)",
    company: "Metro Health Hospital",
    location: "Miami, FL",
    work_type: "On-site",
    type: "Internship",
    experience: "Immediate",
    salary: "$25 - $30 per hour",
    description:
      "Provide direct patient care in a fast-paced emergency room environment. Assess patient conditions, administer medications, and collaborate with physicians.",
    requirements: [
      "Valid RN license in Florida or in final year of nursing program",
      "BLS certification",
      "Strong assessment skills",
      "Eagerness to learn",
    ],
    skills: [
      "Nursing",
      "Patient Care",
      "Emergency Medicine",
      "Triage",
      "Medication Administration",
      "EMR Systems",
      "Critical Thinking",
    ],
    benefits: [
      "Shift differentials",
      "Mentorship",
      "Clinical hours for program completion",
      "Potential for hire",
    ],
  },
];
